spring:
  application:
    name: api_events_sports
    version: ${APP_VERSION:1.0.0}
    environment: ${APP_ENV:development}
    uuid: ${APP_UUID:d2883651-1d92-433c-93ff-55d90670950b}
    url: ${APP_URL:http://localhost:9000}

  profiles:
    active: ${database.provider:mysql}

  mail:
    host: ${MAIL_HOST:smtp.mail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:[EMAIL_ADDRESS]}
    password: ${MAIL_PASSWORD:[PASSWORD]}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: ${MAIL_SMTP_SSL_ENABLE:false}

  flyway:
    enabled: false
    # locations: filesystem:scripts/db/migrations/${database.provider:mysql}
    # baseline-on-migrate: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

providers:
  smtp:
    enabled: ${SMTP_ENABLED:true}
  sendgrid:
    enabled: ${SENDGRID_ENABLED:false}

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics, liveness, readiness
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  port: ${SERVER_PORT:9000}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/}
  error:
    whitelabel:
      enabled: false

app:
  security:
    jwt:
      secret: ${JWT_SECRET:3cfa76ef14937c1c0ea519f8fc057a80fcd04a74ac2b9bd91000223f108f3e58}
      expiration: ${JWT_EXPIRATION:86400}
    admin:
      email: ${ADMIN_USER_EMAIL:admin@sportsevents.com}
      password: ${ADMIN_USER_PASSWORD:Prueba123+}
      username: ${ADMIN_USER_USERNAME:admin}
      first-name: ${ADMIN_USER_FIRST_NAME:Admin}
      last-name: ${ADMIN_USER_LAST_NAME:SportsEvents}
      phone: ${ADMIN_USER_PHONE:+573001234567}
      role: ${ADMIN_USER_ROLE:ADMIN}

